[pytest]
addopts = -vs --alluredir=reports/allure-results
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 核心冒烟用例
    login: 登录相关用例
